# Site settings
title: Programmation Web
author: Sawssen Hariz
email: sawssenhariz@yahoo.fr
description: "Apprendre à programmer des sites et applications Web en utilisants HTML5, CSS3 et JavaScript"
logo: "/imgs/logo-256x256.png"
lang: fr_FR
baseurl: ""
url: "https://programmation-web.com"
repo: https://github.com/lejenome/web-101

source: ./src
destination: ./www
includes_dir: _includes
exclude: [config.xml, node_modules]

# Build settings
markdown: kramdown
# permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-paginate-v2
  # - jekyll-feed

paginate: nil
paginate_path: nil
pagination:
  enabled: false

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  cours:
    output: true
  tp:
    output: true
  quiz:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      seo:
        type: Course
      image:
        path: /imgs/logo-256x256.png
        height: 256
        width: 256
  -
    scope:
      path: ""
      type: cours
    values:
      layout: cours
      embed: true
  -
    scope:
      path: ""
      type: tp
    values:
      layout: tp
      bootstrap: true
      embed: true
  -
    scope:
      path: ""
      type: quiz
    values:
      layout: quiz
      bootstrap: true
      quiz: true
